server:
  port: 80
spring:
  application:
    name: cloud-consumerconsul-order

  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        service-name: ${spring.application.name}
      port: 8500